config/routes.rb
Rails.application.routes.draw do
	#post 'api/auth/sign_in', to: 'users#data'
	 resources :users 
	 #post   'user_token'      => 'user_token#create'
	 #post 'api/auth/sign_in', to: 'users#authentication' 
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
     
    require 'rest-client'

    # def index
    #   #@users = User.all
    # end

    def new
        @user = User.new
    end

    #  def show
    #      user = User.find(params[:id])
    #     render json: user
    # end


    # POST /register
    def create
        # @user = User.new
        #raise @user.inspect
        #if @user.save
        #raise params.inspect
        #url = 'http://localhost:3000/api/auth/sign_in'
        response = RestClient::Request.execute(method: :post, url: url, payload: '{"email": "", "password": " "}', headers: {"Content-Type" => "application/json"})
        #response = RestClient::Request.execute(method: :post, url: url, payload: {email: "email", password: "password"}, headers: {"Content-Type" => "application/json"})

        #response = RestClient.post(url, headers:{"Content-Type" => "text" "email"::email})
        #render json: response
        response = { message: 'User created successfully'}
        render json: response, status: :created 
        #else
            #render json: @user.errors, status: :bad
        #end 
    end

 
    def edit

    end

  #   def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy
  #   redirect_to @user
  # end


    private
    def user_params
      #params.require(:user).permit(:email, :password, :password_digest)
    end
end



        

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apidemofech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div><br>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div><br>

  
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit </h1>
<%#= render "form" %>

app/views/users/index.html.erb
<!-- <h1>user</h1>

<table>
    <thead>
        <tr>
            <td>User-Name</td>
            <td>User-Email</td>
            <td>User-Password</td>
        </tr>
    </thead>
    <tbody> -->
        <%#@users.each do |user| %>
        <!-- <tr>
        <td><%#= user.name %></td>
        <td><%#= user.email %></td>
        <td><%#= user.password_digest %></td>
        
        <td><%#= link_to "delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>|</td>
        </tr>
        <%# end %>
    </tbody>
</table>
 -->

app/views/users/new.html.erb
<h1>sign in</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>